### ISSUE TITLE
Runtime Exception occurred while running the program to convert html to pdf document in Mac OS using wkhtml

### ISSUE THREAD

**Issue by Junaid051983** [jhonnymertz/java-wkhtmltopdf-wrapper#26]
Mac OS X
java.lang.RuntimeException
	at com.github.jhonnymertz.wkhtmltopdf.wrapper.configurations.WrapperConfig.findExecutable(WrapperConfig.java:46)
	at com.github.jhonnymertz.wkhtmltopdf.wrapper.configurations.WrapperConfig.<init>(WrapperConfig.java:14)
	at com.github.jhonnymertz.wkhtmltopdf.wrapper.Pdf.<init>(Pdf.java:36)
	at com.tgt.html_to_pdf_converter.HtmlToPdfConverter_Usingwkhtlwrapper.main(HtmlToPdfConverter_Usingwkhtlwrapper.java:13)
Mac OS X
Exception in thread "main" java.io.IOException: Cannot run program "wkhtmltopdf": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at com.github.jhonnymertz.wkhtmltopdf.wrapper.Pdf.getPDF(Pdf.java:95)
	at com.tgt.html_to_pdf_converter.HtmlToPdfConverter_Usingwkhtlwrapper.main(HtmlToPdfConverter_Usingwkhtlwrapper.java:29)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

**Comment by jhonnymertz** [comment]
It seems you do not have "wkhtmltopdf" command in your path. You can set a custom path to it by using the class `WrapperConfig`. Like this:

`Pdf pdf = new Pdf(new WrapperConfig("path\to\wkhtmltopdf"));`
