### ISSUE TITLE
Support multiple htmlAsString input files

### ISSUE THREAD

**Issue by dloehr** [jhonnymertz/java-wkhtmltopdf-wrapper#8]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1847

```
PdfService pdf = ...;
pdf.addPage(..., PageType.htmlAsString);
pdf.addPage(..., PageType.htmlAsString);
pdf.getPdf();
```

The exception happens the second time you try to close STDIN:
```
java.io.IOException: Stream Closed
        at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_45]
        at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_45]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_45]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_45]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158) ~[na:1.8.0_45]
        at br.eti.mertz.wkhtmltopdf.wrapper.Pdf.getPDF(Pdf.java:78) ~[pdf-service.jar!/:na]
```

I think it'd be nice if the Java wrapper noticed that there are multiple ```htmlAsString``` inputs, and created temporary files for them.

**Comment by jhonnymertz** [comment]
Thanks for the report and sorry for the late reply.

Yeah, probably the solution involves the creation of those temporary files. However, I think it is necessary to sleep a bit on it in order to deal with OS permission constraints.

I think it is easy to verify that there are multiple `htmlAsString`. Also, a temporary folder can be defined in the wrapper settings. We can start from this.
